name: icalendar-web-filter
services:
  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules 
    ports:
      - 3013:3000
    environment:
      - PORT=3000
      - TZ=Europe/Paris
    restart: unless-stopped